systems:
  basedir: ".logs/"
  vis_every: 1500
  # ckpt: "/home/nico/HexPlane-with-TUM-RGBD/.logs/100k_TV_t_s_20/tum_rgbd.th"

model:
  model_name: "HexPlane"
  # N_voxel_init: 8000000
  time_grid_init: 40
  time_grid_final: 680 # according to github, this should be set to frame_number - 1
  upsampling_type: aligned
  upsample_list: [1000, 1200, 1300]
  update_emptymask_list: [15000, 25000, 45000, 60000]

  depth_loss: True
  depth_loss_weight: 0.01

  # density_n_comp: [24, 12, 12]
  # app_n_comp: [48, 24, 24]
  fea2denseAct: relu

  TV_t_s_ratio: 20

  TV_weight_density: 0.005
  TV_weight_app: 0.0005

  fusion_one: "multiply"
  fusion_two: "multiply"
  init_scale: 0.9
  init_shift: 0.5
  density_dim: 8
  DensityMode: "general_MLP"

  # density_featureC: 256
  # app_featureC: 256


data:
  dataset_name: bonn_slam
  scene_bbox_min: [-1.0, -1.0, -1.0]
  scene_bbox_max: [1.0, 1.0, 1.0]
  N_vis: -1

  datasampler_type: rays
  key_f_num: 30
  downsample: 1.0

  cal_fine_bbox: True

optim:
  n_iters: 100000
  batch_size: 128

render_only: False
render_test: True
render_path: True
expname: tum_rgbd
