systems:
  basedir: ".logs/"
  vis_every: 1000
  # ckpt: "/home/nico/HexPlane-with-TUM-RGBD/.logs/tum_rgbd-20230807-082932/tum_rgbd.th"

model:
  # model_name: "HexPlane"
  N_voxel_init: 262144
  time_grid_init: 25 # according to github, this should be set to 0.25 * frame_number
  time_grid_final: 100 # according to github, this should be set to frame_number
  upsampling_type: aligned

  upsample_list: [3000, 5000, 7000]
  update_emptymask_list: [2000, 4000, 6000, 8000]

  # depth_loss: False
  # depth_loss_weight: 0.01

  density_n_comp: [24, 12, 12]
  app_n_comp: [48, 24, 24]
  fea2denseAct: relu

  # TV_t_s_ratio: 500

  TV_weight_density: 0.005
  TV_weight_app: 0.0005

  # density_t_pe: 2
  # density_pos_pe: 2
  # density_view_pe: 2

  # app_t_pe: 2
  # app_pos_pe: 2

data:
  # datadir: ""
  datadir: "/media/nico/TOSHIBA EXT/rgbd_bonn_dataset/rgbd_bonn_moving_nonobstructing_box"
  dataset_name: tum_rgbd
  scene_bbox_min: [-5, -5, -5]
  scene_bbox_max: [5, 5, 5]
  N_vis: 1

  datasampler_type: rays
  key_f_num: 30
  downsample: 1.0

  cal_fine_bbox: True

optim:
  n_iters: 20000

render_test: False
render_path: True
expname: tum_rgbd
# render_only: True
