systems:
  basedir: "./logs"
  vis_every: 1

model:
  N_voxel_init: 262144
  time_grid_init: 31
  time_grid_final: 300
  upsampling_type: aligne
  upsample_list: [70000, 140000, 210000]
  update_emptymask_list: [50000, 100000, 150000, 220000]

  density_n_comp: [24, 12, 12]
  app_n_comp: [48, 24, 24]
  fea2denseAct: relu
  app_view_pe: 0
  app_fea_pe: 0

  TV_weight_density: 0.0005
  TV_weight_app: 0.0005


data:
  datadir: "./data/rgbd_dataset_freiburg3_sitting_static"
  dataset_name: tum_rgbd
  scene_bbox_min: [-2.5, -2.0, -1.0]
  scene_bbox_max: [2.5, 2.0, 1.0]
  N_vis: 5

  datasampler_type: rays
  stage_1_iteration: 200
  stage_2_iteration: 0
  stage_3_iteration: 0
  key_f_num: 30
  downsample: 1.0

optim:
  n_iters: 200

render_test: True
render_path: True
expname: tum_rgbd
