systems:
  basedir: ".logs/"
  vis_every: 10000
  # was 50000

model:
  N_voxel_init: 262144
  # TODO: Adjust these values
  time_grid_init: 16 # int(685*0.24)*0.5 - > 685 is frame rate
  time_grid_final: 24 # TODO: try different params
  upsampling_type: unaligned
  upsample_list: [3000, 6000, 9000]
  update_emptymask_list: [4000, 8000, 10000]

  #density_n_comp: [24, 12, 12]
  #app_n_comp: [48, 24, 24]
  #fea2denseAct: relu
  #app_view_pe: 0
  #app_fea_pe: 0
  #TV_weight_density: 0.0005
  #TV_weight_app: 0.0005

data:
  datadir: "./data/rgbd_dataset_freiburg3_sitting_static"
  dataset_name: tum_rgbd_slam
  scene_bbox_min: [-1.9219, -1.4237, -1.0000]
  scene_bbox_max: [1.6996,  1.6841, 18.7600]
  N_vis: 5

  datasampler_type: rays
  #stage_1_iteration: 300000
  #stage_2_iteration: 250000
  #stage_3_iteration: 100000
  #key_f_num: 30
  downsample: 1.0

optim:
  # n_iters: 650000
  n_iters: 40000

render_test: True
render_path: True
expname: tum_rgbd_slam
